'use strict';
/**
 * Builds a synthetic repository that contains every kind of context waste
 * ctxray claims to detect, so the test suite can assert on real numbers rather
 * than mocks. Returns the temp directory path.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

function w(root, rel, content) {
  const p = path.join(root, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

function lorem(lines, prefix = 'const value') {
  const out = [];
  for (let i = 0; i < lines; i++) {
    out.push(`${prefix}${i} = computeSomething(${i}, "argument-${i}", { retries: ${i % 5} });`);
  }
  return out.join('\n');
}

function build() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ctxray-fixture-'));

  // ---- real source ---------------------------------------------------------
  w(root, 'package.json', JSON.stringify({
    name: 'demo-app', version: '2.1.0', main: 'src/index.js',
    scripts: { test: 'jest', build: 'tsc' },
    dependencies: { express: '^4.19.0', zod: '^3.23.0' },
  }, null, 2));
  w(root, 'README.md', `# demo-app\n\nA service that does the thing.\n\n${'Explanatory prose. '.repeat(60)}\n`);
  w(root, 'src/index.js', `const express = require('express');\n${lorem(120)}\nmodule.exports = { start };\n`);
  w(root, 'src/routes/users.js', lorem(200, 'const userHandler'));
  w(root, 'src/routes/orders.js', lorem(180, 'const orderHandler'));
  w(root, 'src/lib/db.js', lorem(90, 'const query'));
  w(root, 'src/lib/auth.js', lorem(75, 'const token'));
  w(root, 'tests/users.test.js', lorem(60, 'test'));

  // ---- lockfile (committed, huge, useless to an agent) --------------------
  const lockDeps = {};
  for (let i = 0; i < 900; i++) {
    lockDeps[`node_modules/pkg-${i}`] = {
      version: `1.${i}.0`,
      resolved: `https://registry.npmjs.org/pkg-${i}/-/pkg-${i}-1.${i}.0.tgz`,
      integrity: `sha512-${'x'.repeat(86)}==`,
      engines: { node: '>=14' },
    };
  }
  w(root, 'package-lock.json', JSON.stringify({ name: 'demo-app', lockfileVersion: 3, packages: lockDeps }, null, 2));

  // ---- build output --------------------------------------------------------
  w(root, 'dist/bundle.js', lorem(400, 'var _0x' ));
  w(root, 'dist/vendor.min.js', `!function(e,t){${'a'.repeat(60000)}}(window,document);`);
  w(root, 'dist/bundle.js.map', JSON.stringify({ version: 3, sources: ['a.js'], mappings: 'AAAA'.repeat(5000) }));

  // ---- generated code ------------------------------------------------------
  w(root, 'src/generated/api_pb2.py', `# Code generated by the protocol buffer compiler. DO NOT EDIT!\n${lorem(300, 'FIELD')}`);
  w(root, 'src/types/schema.generated.ts', `// @generated\n${lorem(250, 'export type T')}`);

  // ---- snapshots and fixtures ---------------------------------------------
  w(root, 'tests/__snapshots__/users.test.js.snap', `exports[\`renders\`] = \`\n${'<div class="row">cell</div>\n'.repeat(1200)}\`;\n`);
  w(root, 'tests/fixtures/sample-response.json', JSON.stringify(
    Array.from({ length: 500 }, (_, i) => ({ id: i, name: `user${i}`, email: `u${i}@example.com`, meta: { a: 1, b: 2 } })), null, 2));

  // ---- bulk data -----------------------------------------------------------
  const rows = ['id,name,email,country,signup_date,plan,mrr'];
  for (let i = 0; i < 4000; i++) rows.push(`${i},User ${i},user${i}@example.com,US,2026-01-01,pro,49`);
  w(root, 'data/customers.csv', rows.join('\n'));

  // ---- duplicates ----------------------------------------------------------
  const shared = lorem(120, 'const helper');
  w(root, 'src/lib/format.js', shared);
  w(root, 'src/routes/format.js', shared);
  w(root, 'scripts/format.js', shared);

  // ---- binary --------------------------------------------------------------
  w(root, 'assets/logo.png', Buffer.alloc(180000, 7));
  w(root, 'assets/hero.jpg', Buffer.alloc(240000, 9));

  // ---- large svg -----------------------------------------------------------
  w(root, 'assets/map.svg', `<svg xmlns="http://www.w3.org/2000/svg">${'<path d="M0 0 L10 10 L20 5 Z"/>'.repeat(2000)}</svg>`);

  // ---- doc archive ---------------------------------------------------------
  w(root, 'CHANGELOG.md', Array.from({ length: 400 }, (_, i) => `## v1.${i}.0\n\n- Fixed a thing in module ${i}\n- Bumped a dependency\n`).join('\n'));

  // ---- gitignored content (should be skipped by default) ------------------
  w(root, '.gitignore', 'node_modules/\ncoverage/\n*.tmp\n.env\n');
  w(root, 'node_modules/left-pad/index.js', lorem(50));
  w(root, 'coverage/lcov-report/index.html', '<html>' + 'x'.repeat(50000) + '</html>');
  w(root, 'scratch.tmp', 'x'.repeat(20000));

  return root;
}

module.exports = { build };

if (require.main === module) {
  process.stdout.write(build() + '\n');
}
