'use strict';
/**
 * `ctxray init` — turn findings into files.
 *
 * Writes two things:
 *   .agentignore  a tuned exclusion list, derived from what the scan actually
 *                 found in THIS repo rather than a generic boilerplate list.
 *   AGENTS.md     a starter context file with the repo's real shape filled in
 *                 (languages, entry points, layout, and the exclusions above).
 *
 * .agentignore is read by ctxray itself and is the emerging convention several
 * agent runners look for. The file is also valid .gitignore syntax, so you can
 * `cat .agentignore >> .cursorignore` or point any other tool at it.
 */

const fs = require('fs');
const path = require('path');
const { CATEGORY_LABEL } = require('./classify');
const { num } = require('./ui');

/**
 * Collapse flagged files into the smallest set of glob patterns that covers
 * them, preferring directory patterns over long file lists.
 */
function derivePatterns(report) {
  const flagged = report.files.filter((f) => f.waste);
  const dirHits = new Map();   // dir -> {flagged, total, tokens}
  const totalsByDir = new Map();

  for (const f of report.files) {
    const parts = f.path.split('/');
    for (let i = 1; i < parts.length; i++) {
      const dir = parts.slice(0, i).join('/');
      const t = totalsByDir.get(dir) || { total: 0, flagged: 0, tokens: 0 };
      t.total++;
      if (f.waste) { t.flagged++; t.tokens += f.tokens; }
      totalsByDir.set(dir, t);
    }
  }

  // A directory is worth a pattern when nearly everything in it is waste.
  const dirPatterns = [];
  const covered = new Set();
  const sortedDirs = [...totalsByDir.entries()].sort((a, b) => a[0].split('/').length - b[0].split('/').length);
  for (const [dir, t] of sortedDirs) {
    if (t.flagged < 2 || t.flagged / t.total < 0.9) continue;
    // Skip if an ancestor already covers it.
    let ancestorCovered = false;
    for (const d of dirPatterns) {
      if (dir === d.dir || dir.startsWith(`${d.dir}/`)) { ancestorCovered = true; break; }
    }
    if (ancestorCovered) continue;
    dirPatterns.push({ dir, files: t.flagged, tokens: t.tokens });
  }
  for (const d of dirPatterns) {
    for (const f of flagged) {
      if (f.path === d.dir || f.path.startsWith(`${d.dir}/`)) covered.add(f.path);
    }
  }

  // Remaining flagged files, grouped by category, expressed as extension globs
  // where an extension is uniformly waste, otherwise as literal paths.
  const rest = flagged.filter((f) => !covered.has(f.path));
  const extStats = new Map();
  for (const f of report.files) {
    const ext = path.posix.extname(f.path).toLowerCase();
    if (!ext) continue;
    const s = extStats.get(ext) || { total: 0, flagged: 0, tokens: 0 };
    s.total++;
    if (f.waste && !covered.has(f.path)) { s.flagged++; s.tokens += f.tokens; }
    extStats.set(ext, s);
  }
  const extPatterns = [];
  for (const [ext, s] of extStats) {
    if (s.flagged >= 3 && s.flagged / s.total >= 0.95) {
      extPatterns.push({ pattern: `*${ext}`, files: s.flagged, tokens: s.tokens });
      for (const f of rest) {
        if (path.posix.extname(f.path).toLowerCase() === ext) covered.add(f.path);
      }
    }
  }

  const filePatterns = flagged
    .filter((f) => !covered.has(f.path))
    .sort((a, b) => b.tokens - a.tokens)
    .map((f) => ({ pattern: f.path, files: 1, tokens: f.tokens, reason: f.waste.reason, category: f.waste.category }));

  return {
    dirs: dirPatterns.sort((a, b) => b.tokens - a.tokens),
    exts: extPatterns.sort((a, b) => b.tokens - a.tokens),
    files: filePatterns,
  };
}

const RULE_WIDTH = 74;

/**
 * Section header comment, e.g.
 *   # ---- lockfiles ································· 79k tok · 1 file
 *
 * Counts live in the HEADER, never at the end of a pattern line. gitignore has
 * no inline comments — `dist/ # 24k tok` is a literal path containing spaces
 * and a hash, so an annotated pattern silently matches nothing. This bit us
 * once; the test suite now asserts that no pattern line contains a '#'.
 */
function section(label, tokens, files) {
  const right = files === undefined
    ? ''
    : ` ${num(tokens)} tok · ${files} file${files === 1 ? '' : 's'}`;
  const left = `# ---- ${label} `;
  const fill = Math.max(3, RULE_WIDTH - left.length - right.length);
  return left + '·'.repeat(fill) + right;
}

function buildAgentIgnore(report, patterns) {
  const t = report.totals;
  const lines = [];
  lines.push('# .agentignore — generated by ctxray');
  lines.push(`# ${new Date().toISOString().slice(0, 10)} · ${t.files} files scanned · ${num(t.tokens)} tokens total`);
  lines.push('#');
  lines.push('# Everything below was flagged as content a coding agent pays for but');
  lines.push('# cannot use. Delete any line you disagree with — this is a starting');
  lines.push('# point derived from your repo, not a rule.');
  lines.push('#');
  lines.push(`# Estimated saving: ${num(t.reclaimableTokens)} tokens per full-context pass.`);
  lines.push('#');
  lines.push('# Syntax is .gitignore syntax, so this file also works as a .cursorignore,');
  lines.push('# .aiexclude, or an addition to your existing .gitignore.');
  lines.push('');

  if (patterns.dirs.length) {
    const tot = patterns.dirs.reduce((s, d) => s + d.tokens, 0);
    const nf = patterns.dirs.reduce((s, d) => s + d.files, 0);
    lines.push(section('directories that are almost entirely non-source', tot, nf));
    for (const d of patterns.dirs) lines.push(`${d.dir}/`);
    lines.push('');
  }

  if (patterns.exts.length) {
    const tot = patterns.exts.reduce((s, e) => s + e.tokens, 0);
    const nf = patterns.exts.reduce((s, e) => s + e.files, 0);
    lines.push(section('file types that are never useful here', tot, nf));
    for (const e of patterns.exts) lines.push(e.pattern);
    lines.push('');
  }

  // Group the individual files by category so the file reads as an argument.
  const byCat = new Map();
  for (const f of patterns.files) {
    const g = byCat.get(f.category) || [];
    g.push(f);
    byCat.set(f.category, g);
  }
  const cats = [...byCat.entries()].sort((a, b) =>
    b[1].reduce((s, x) => s + x.tokens, 0) - a[1].reduce((s, x) => s + x.tokens, 0));

  for (const [cat, group] of cats) {
    const label = (CATEGORY_LABEL[cat] || cat).toLowerCase();
    const catTokens = group.reduce((s, x) => s + x.tokens, 0);
    group.sort((a, b) => b.tokens - a.tokens);
    lines.push(section(label, catTokens, group.length));
    if (group[0] && group[0].reason) lines.push(`# ${group[0].reason}`);
    for (const f of group.slice(0, 80)) lines.push(f.pattern);
    if (group.length > 80) {
      lines.push(`# … ${group.length - 80} more in this category were omitted; see: ctxray --json`);
    }
    lines.push('');
  }

  lines.push(section('safety net: things no scan should have to re-discover'));
  lines.push('.git/');
  lines.push('node_modules/');
  lines.push('.venv/');
  lines.push('__pycache__/');
  lines.push('*.log');
  lines.push('*.map');
  lines.push('');
  return lines.join('\n');
}

const ENTRY_HINTS = [
  'main.py', 'app.py', '__main__.py', 'manage.py', 'wsgi.py', 'asgi.py',
  'index.js', 'index.ts', 'main.js', 'main.ts', 'server.js', 'server.ts', 'app.ts', 'app.js',
  'main.go', 'main.rs', 'lib.rs', 'Program.cs', 'Application.java',
];

function buildAgentsMd(report, patterns) {
  const t = report.totals;
  // Language mix of the code an agent should actually read. Using the raw
  // totals here would announce "primary language: JSON" on any repo with a
  // committed lockfile, which is exactly the confusion this file exists to end.
  const langs = report.languages
    .map((l) => ({ ...l, signalTokens: l.tokens - l.wasteTokens }))
    .filter((l) => l.language !== 'Binary' && l.signalTokens > (t.signalTokens || 1) * 0.02)
    .sort((a, b) => b.signalTokens - a.signalTokens)
    .slice(0, 6);
  const primaryLang = langs.length ? langs[0].language : 'unknown';

  const entries = report.files
    .filter((f) => !f.waste && ENTRY_HINTS.includes(path.posix.basename(f.path)))
    .sort((a, b) => a.path.split('/').length - b.path.split('/').length)
    .slice(0, 6);

  const topDirs = report.directories
    .map((d) => ({ ...d, signalTokens: d.tokens - d.wasteTokens }))
    .filter((d) => d.dir !== '.' && d.signalTokens > (t.signalTokens || 1) * 0.03)
    .sort((a, b) => b.signalTokens - a.signalTokens)
    .slice(0, 10);

  const manifests = report.files
    .filter((f) => ['package.json', 'pyproject.toml', 'Cargo.toml', 'go.mod', 'pom.xml', 'build.gradle', 'Gemfile', 'composer.json', 'requirements.txt'].includes(path.posix.basename(f.path)) && f.path.split('/').length <= 2)
    .map((f) => f.path);

  const L = [];
  L.push('# AGENTS.md');
  L.push('');
  L.push('> Scaffolded by `ctxray init`. The structure below was read off the repo;');
  L.push('> the prose in **bold brackets** is yours to fill in. Delete this note when done.');
  L.push('');
  L.push('## What this project is');
  L.push('');
  L.push('**[One paragraph: what it does, who uses it, what "done" looks like for a change.]**');
  L.push('');
  L.push('## Shape of the codebase');
  L.push('');
  L.push(`Primary language: **${primaryLang}**. ` +
    `${t.signalFiles.toLocaleString()} source files, roughly ${num(t.signalTokens)} tokens of real code.`);
  L.push('');
  if (langs.length > 1) {
    L.push('| Language | Files | Share of the source |');
    L.push('| --- | ---: | ---: |');
    for (const l of langs) {
      L.push(`| ${l.language} | ${l.files} | ${((l.signalTokens / (t.signalTokens || 1)) * 100).toFixed(0)}% |`);
    }
    L.push('');
  }
  if (topDirs.length) {
    L.push('| Directory | Weight | What lives here |');
    L.push('| --- | ---: | --- |');
    for (const d of topDirs) {
      L.push(`| \`${d.dir}/\` | ${num(d.signalTokens)} tok | **[describe]** |`);
    }
    L.push('');
  }
  if (entries.length) {
    L.push('Entry points:');
    L.push('');
    for (const e of entries) L.push(`- \`${e.path}\``);
    L.push('');
  }
  if (manifests.length) {
    L.push(`Dependency manifests: ${manifests.map((m) => `\`${m}\``).join(', ')}`);
    L.push('');
  }

  L.push('## Commands');
  L.push('');
  L.push('```bash');
  L.push('# install   **[fill in]**');
  L.push('# test      **[fill in]**');
  L.push('# lint      **[fill in]**');
  L.push('# run       **[fill in]**');
  L.push('```');
  L.push('');
  L.push('Always run the test and lint commands before declaring a change finished.');
  L.push('');

  L.push('## Conventions');
  L.push('');
  L.push('**[House style: error handling, naming, how tests are organised, what');
  L.push('reviewers reject. Be specific — a rule an agent cannot check is not a rule.]**');
  L.push('');

  L.push('## Do not read these');
  L.push('');
  L.push(`This repo carries ${num(t.wasteTokens)} tokens (${((t.wasteTokens / (t.tokens || 1)) * 100).toFixed(0)}%) of content that costs money and teaches nothing. `);
  L.push('`.agentignore` has the full list. The large items:');
  L.push('');
  const top = report.wasteCategories.slice(0, 6);
  if (top.length) {
    L.push('| Category | Tokens | Why skip it |');
    L.push('| --- | ---: | --- |');
    for (const cat of top) {
      const label = CATEGORY_LABEL[cat.category] || cat.category;
      L.push(`| ${label} | ${num(cat.tokens)} | ${cat.examples[0] ? cat.examples[0].reason : '—'} |`);
    }
    L.push('');
  }

  L.push('## When you need something that is excluded');
  L.push('');
  L.push('Read the specific file on demand rather than pulling the whole directory.');
  L.push('For bulk data, read the schema and a handful of rows, never the file.');
  L.push('');
  L.push('---');
  L.push('');
  L.push(`<sub>Context budget generated by [ctxray](https://github.com/geraltbhai/ctxray) on ${new Date().toISOString().slice(0, 10)}.</sub>`);
  L.push('');
  return L.join('\n');
}

/**
 * @returns {{written: string[], skipped: string[], patterns: object}}
 */
function init(report, opts = {}) {
  const patterns = derivePatterns(report);
  const written = [];
  const skipped = [];

  const targets = [
    { name: opts.ignoreName || '.agentignore', content: buildAgentIgnore(report, patterns) },
  ];
  if (opts.agentsMd !== false) {
    targets.push({ name: 'AGENTS.md', content: buildAgentsMd(report, patterns) });
  }

  for (const target of targets) {
    const dest = path.join(report.root, target.name);
    if (fs.existsSync(dest) && !opts.force) {
      skipped.push(target.name);
      continue;
    }
    if (!opts.dryRun) fs.writeFileSync(dest, target.content, 'utf8');
    written.push(target.name);
  }

  return { written, skipped, patterns, preview: targets };
}

module.exports = { init, derivePatterns, buildAgentIgnore, buildAgentsMd };
